name: Deploy Vite + React to GitHub Pages

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Remove global npm registry settings (if any)
        run: npm config delete registry

      - name: Force npm to use public registry
        run: npm config set registry https://registry.npmjs.org/

      - name: Verify npm registry
        run: npm config get registry  # This should output: https://registry.npmjs.org/

      - name: Install dependencies
        run: npm install

      - name: Set Vite base path for GitHub Pages
        run: echo "VITE_BASE=ramonratcliffe/ramonratcliffe.github.io/" >> $GITHUB_ENV

      - name: Build project
        run: npm run build
        env:
          VITE_BASE: "/ramonratcliffe.github.io/"

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./dist

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
